### ISSUE TITLE
AdMob policy violation warning... :(

### ISSUE THREAD

**Issue by zlutor** [FalsinSoft/QtAndroidTools#30]
Today I've got the following warning in AdMob policy center: 

![image](https://user-images.githubusercontent.com/12124689/113321246-afeae280-9313-11eb-8aed-a6e1dcfe0951.png)

I bet it is not an April's Fool joke - but I've not seen any app doing it, especially the latter one, asking consent before showing every ads?! users will be totally unhappy and they will opt-out the whole stuff... :(

Are you planning to provide some common solution addressing this concern or we should do it per application base?

Thx,

Zoltan

**Comment by FalsinSoft** [comment]
Hi

Unfortunately doesn't seem to exist a common solution.  The policy of AdMod Rewarded Ads are:

1. The user must know (by your UI) the action will bring a video AD and they must know the exact reward they will get after watching the video AD. The button or icon must show 2 things to your user: will show video AD and reward.
2. The App can't play the AD automatically. for example, if you play rewarded AD when user exits the app, this is not allowed, because the user doesn't know they will see an AD at leaving.
3. The user must have other options if they doesn't want to watch the video AD.

Official explanation [here](https://support.google.com/admob/answer/7313578?hl=en). Refer to "Rewarded Ad Format specific policies" section. Me too don't understand how google can check every app for verify if this policy is respected. In your case I suspect some user reported your app to google but it's just a guess.

**Comment by zlutor** [comment]
thx, I will handle it in the apps...
