### ISSUE TITLE
Sharing an image in data folder

### ISSUE THREAD

**Issue by edips** [FalsinSoft/QtAndroidTools#45]
Hi. I try to share an image generated and saved by QML Canvas. I cannot share an image in Android's writable data folder (/storage/emulated/0/Android/data/org.project.geoclasslite/files/sharedfiles/logo_falsinsoft.jpg) . I copied and pasted the image into Download path. The code didn't work;
`QtAndroidSharing.shareBinaryData("image/jpeg", QtAndroidSystem.downloadLocation + "/sharedfiles/logo_falsinsoft.jpg")`
 Is it possible to share an image in Android's  data folder or an image in QStandardPaths::DownloadLocation? 
Thank you

**Comment by FalsinSoft** [comment]
Hi
If you read the library documentation you should know the path from where the image can be shared must be indicated inside the app manifest file using the following block:

```
<provider android:name="androidx.core.content.FileProvider"
          android:authorities="${applicationId}.qtandroidtoolsfileprovider"
          android:grantUriPermissions="true"
          android:exported="false">
    <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/sharedfilepaths"/>
</provider>
```

I don't know if you can set a path outside the app private writable space but I think no cause the file scoped storage introduced in the last android versions as explained [here](https://developer.android.com/about/versions/11/privacy/storage). However I didn't try because the standard behavior is to use the app private space also to keep the file private.

**Comment by edips** [comment]
Thank you very much! After adding this to sharedfilepaths.xml, it worked:
```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
<external-path name="my_images"
    path="Android/data/org.project.myapp/files/Pictures" />
</paths>
```
