### ISSUE TITLE
Error: making it incompatible with Gradle 6.0

### ISSUE THREAD

**Issue by ssakone** [FalsinSoft/QtAndroidTools#8]
> Task :mergeDebugJavaResource FAILED
> Task :mergeExtDexDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'META-INF/DEPENDENCIES'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5.1/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by FalsinSoft** [comment]
Hi
I guess you tried to compile the master branch instead of switch to the latest tagged version as written in the project description. This error came from a missed part inside gradle file that I forgot to include during the porting to Qt 5.14 compile configuration. I fixed the problem in the subsequent commit. If you update your local repository you should be able to compile now.
Keep me informed about it.

**Comment by FalsinSoft** [comment]
Hi
Can you confirm the issue is resolved with the latest commit?

**Comment by ssakone** [comment]
Yes all done thanks
